####this is my docker compose file, i dont know if it will work but it is a start

version: '3.3'
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mynet
  api:
    build: .
    container_name: api
    ports:
      - "80:4000"
    links:
      - redis
    depends_on:
      - redis
    networks:
      - mynet
    environment:
      REDIS_HOST: "127.0.0.1"
      REDIS_PORT: 6379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
networks:
  mynet:
    driver: bridge
volumes:
  redis_data: