####this is my docker compose file, i dont know if it will work but it is a start

version: '3.3'
services:
  redis:
    image: redis:alpine
    ports:
      - "4000:6379"
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    volumes:
      - redis_data:/data
    networks:
      - mynet
  api:
    build: .
    ports:
      - "80:4000"
    depends_on:
      - redis
    networks:
      - mynet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
networks:
  mynet:
    driver: bridge
volumes:
  redis_data: